name: BetterTrainDestroy
version: ${project.version}
main: mikeshafter.bettertraindestroy.BetterTrainDestroy
api-version: 1.16
authors: [ mikeshafter ]
description: FIGHT ME UNDERSCORE 11

commands:
  TrainDestroyDelay:
    description: Delays TrainDestroy
    permission: TrainDestroy.delay
    usage: /<command>

  reload:
    description: Reloads config
    permission: TrainDestroy.delay
    usage: /<command>

  odometer:
    description: Records minecart distances.
    usage: /<command> <start|record|stop>

permissions:
  TrainDestroy.delay:
    default: op
    description: Permission for /TrainDestroyDelay